@Login_Backend_HostAddress = https://localhost:7045

POST {{Login_Backend_HostAddress}}/sign
Accept: application/json
Content-Type: application/json

{
  "username": "hubertjustin01@gmail.com",
  "password": "dein_Passwort"
}


###
